// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvoywjimbwizlzhynntb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2b3l3amltYndpemx6aHlubnRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjQwOTMsImV4cCI6MjA3Mzk0MDA5M30.ti7F3ryqtyvPWl_Hvny_07BjHMkRA_vhathbIQK3ZiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});